### ISSUE TITLE
dnsmasq lxc depend

### ISSUE THREAD

**Issue by ghost** [lxc/lxc-pkg-ubuntu#1]
Please remove dnsqmasq from required lxc depends.
For example - i use statically addresses for my containers, and don't need dnsmasq for these.
I also use a simplified template Ubuntu, which uses lxc.network.ipv4 from the configuration file of the container because of what I had to remove from the template DHCP using because it caused debris in syslog.

**Comment by stgraber** [comment]
Well, dnsmasq-base is going to be around on any Ubuntu system anyway and making lxc-net entirely optional based on the presence of dnsmasq would make things pretty complicated as that code's upstream.

Instead, if you don't need it, just turn it off in /etc/default/lxc.
