### ISSUE TITLE
bash-completion broken

### ISSUE THREAD

**Issue by AnrDaemon** [lxc/lxc-pkg-ubuntu#4]
https://github.com/lxc/lxc-pkg-ubuntu/commit/c388fdab21c94de3422914b30705166caf2ffaf5 broke bash-completion on 12.04

```
_have: command not found
```

**Comment by ohmer1** [comment]
I confirm, same problem here.

**Comment by stgraber** [comment]
Unfortunately reverting this would break bash completion on more the latest versions of bash & bash-completion so I don't expect us to revert this what with Ubuntu 12.04 LXC being a best effort automatic backport (no supported version of LXC for 12.04).

**Comment by stgraber** [comment]
Well, someone could potentially make yet another debian/rules hack to sed _have for have in the bash completion file and I probably would merge it. Just won't be working on it myself.

**Comment by AnrDaemon** [comment]
Or just remove 2.0 packaging for 12.04. That could be an option as well.

**Comment by stgraber** [comment]
The PPA is auto-generated, if we remove 2.0, you'll end up with the release time LXC of version 0.7, not sure you'll like that downgrade :)

**Comment by AnrDaemon** [comment]
_shrug_ >.<

**Comment by AnrDaemon** [comment]
Ok, which file you were mentioning? Github slows down to a crawl each time I try to browse commits.

**Comment by stgraber** [comment]
https://github.com/lxc/lxc-pkg-ubuntu/blob/dpm-xenial/debian/rules

It'd need some more override_dh_install logic

**Comment by AnrDaemon** [comment]
It may need a move down the block, if 13.10 is also affected. But I do not have a system ready to check.

**Comment by evgeni** [comment]
@stgraber @AnrDaemon this can be closed then?

**Comment by stgraber** [comment]
yup
